#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
ORIGIN=""
START=true

usage() {
  cat <<'EOF'
Secure Docker installer for Chat2API Web Gateway

Usage:
  ./scripts/install.sh --origin https://gateway.example.com
  ./scripts/install.sh --origin http://localhost:8080 --no-start

Options:
  --origin URL  Exact HTTPS admin origin (HTTP is allowed only for localhost)
  --no-start    Generate and validate configuration without starting the stack
  --help        Show this help
EOF
}

fail() {
  printf 'Installation failed: %s\n' "$1" >&2
  exit 1
}

while (($#)); do
  case "$1" in
    --origin)
      (($# >= 2)) || fail "--origin requires a value"
      ORIGIN="$2"
      shift 2
      ;;
    --no-start)
      START=false
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

[[ -n "${ORIGIN}" ]] || fail "provide --origin"
if [[ "${ORIGIN}" == https://* ]]; then
  AUTHORITY="${ORIGIN#https://}"
elif [[ "${ORIGIN}" == http://localhost || "${ORIGIN}" == http://localhost:* || "${ORIGIN}" == http://127.0.0.1 || "${ORIGIN}" == http://127.0.0.1:* ]]; then
  AUTHORITY="${ORIGIN#http://}"
else
  fail "origin must be exact HTTPS, or HTTP on localhost"
fi
[[ -n "${AUTHORITY}" && "${AUTHORITY}" != *"/"* && "${AUTHORITY}" != *"?"* && "${AUTHORITY}" != *"#"* && "${AUTHORITY}" != *"@"* ]] \
  || fail "origin must not include a path, credentials, query, or hash"
command -v docker >/dev/null 2>&1 || fail "Docker is required"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
command -v openssl >/dev/null 2>&1 || fail "OpenSSL is required for secret generation"

if [[ -e "${ENV_FILE}" ]]; then
  fail ".env already exists; preserving it. Use pnpm doctor or remove it manually after backup."
fi

MASTER_KEY="$(openssl rand -base64 32 | tr -d '\n')"
BOOTSTRAP_KEY="$(openssl rand -hex 32)"
ADMIN_TOKEN="$(openssl rand -hex 32)"
SESSION_SECRET="$(openssl rand -hex 48)"
TRUST_PROXY=1
SECURE_COOKIES=true
if [[ "${ORIGIN}" == http://localhost* || "${ORIGIN}" == http://127.0.0.1* ]]; then
  TRUST_PROXY=false
  SECURE_COOKIES=false
fi

TEMP_FILE="$(mktemp "${ROOT}/.env.tmp.XXXXXX")"
trap 'rm -f -- "${TEMP_FILE:-}"' EXIT
cat >"${TEMP_FILE}" <<EOF
# Generated by scripts/install.sh. Keep this file private.
NODE_ENV=production
CHAT2API_HOST=0.0.0.0
PORT=8080
CHAT2API_DATABASE_PATH=/data/chat2api.sqlite
CHAT2API_LOG_LEVEL=info
CHAT2API_TRUST_PROXY=${TRUST_PROXY}
CHAT2API_SECURE_COOKIES=${SECURE_COOKIES}

CHAT2API_MASTER_KEY=${MASTER_KEY}
CHAT2API_BOOTSTRAP_API_KEY=${BOOTSTRAP_KEY}
CHAT2API_ADMIN_TOKEN=${ADMIN_TOKEN}
CHAT2API_SESSION_SECRET=${SESSION_SECRET}
CHAT2API_ADMIN_ORIGINS=${ORIGIN}

CHAT2API_MAX_BODY_BYTES=2097152
CHAT2API_GLOBAL_CONCURRENCY=20
CHAT2API_ACCOUNT_CONCURRENCY=2
CHAT2API_RATE_LIMIT_RPM=60
CHAT2API_DAILY_QUOTA=1000
CHAT2API_REQUEST_TIMEOUT_MS=120000
CHAT2API_FIRST_BYTE_TIMEOUT_MS=30000
CHAT2API_STREAM_IDLE_TIMEOUT_MS=90000
CHAT2API_ACCOUNT_HEALTH_INTERVAL_MS=900000
EOF
chmod 0600 "${TEMP_FILE}"
mv -- "${TEMP_FILE}" "${ENV_FILE}"
trap - EXIT

if ! docker compose --project-directory "${ROOT}" config --quiet; then
  rm -f -- "${ENV_FILE}"
  fail "generated Compose configuration is invalid"
fi

if [[ "${START}" == true ]]; then
  docker compose --project-directory "${ROOT}" up -d --build
  printf 'Waiting for gateway readiness'
  READY=false
  for _ in {1..30}; do
    if docker compose --project-directory "${ROOT}" exec -T gateway \
      node -e "fetch('http://127.0.0.1:8080/health/ready').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" \
      >/dev/null 2>&1; then
      printf '\nGateway is ready.\n'
      READY=true
      break
    fi
    printf '.'
    sleep 2
  done
  [[ "${READY}" == true ]] || fail "gateway did not become ready within 60 seconds"
fi

cat <<EOF

Installation prepared.
Admin URL: ${ORIGIN}/admin/

Retrieve the local admin token only when needed:
  ./scripts/show-admin-token.sh

The token was not printed by this installer.
EOF
