import { randomBytes } from 'node:crypto'
import {
  chmodSync,
  copyFileSync,
  existsSync,
  openSync,
  closeSync,
  readFileSync,
  writeFileSync,
} from 'node:fs'
import { resolve } from 'node:path'
import { createInterface } from 'node:readline/promises'

const root = resolve(import.meta.dirname, '..')
const environmentPath = resolve(root, '.env')

function argument(name) {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function hasFlag(name) {
  return process.argv.includes(name)
}

function fail(message) {
  process.stderr.write(`Setup failed: ${message}\n`)
  process.exit(1)
}

function normalizedOrigin(value) {
  let origin
  try {
    origin = new URL(value)
  } catch {
    fail('admin origin must be a valid URL')
  }
  if (
    !origin
    || !['http:', 'https:'].includes(origin.protocol)
    || origin.origin !== value
    || origin.username
    || origin.password
    || origin.search
    || origin.hash
  ) {
    fail('admin origin must be an exact HTTP(S) origin without path, credentials, query, or hash')
  }
  const isLoopback = ['localhost', '127.0.0.1', '::1'].includes(origin.hostname)
  if (origin.protocol !== 'https:' && !isLoopback) {
    fail('non-loopback admin origins must use HTTPS')
  }
  return origin.origin
}

function secret(bytes = 36) {
  return randomBytes(bytes).toString('base64url')
}

async function resolveOrigin() {
  const provided = argument('--origin')
  if (provided) return normalizedOrigin(provided)
  if (hasFlag('--non-interactive') || !process.stdin.isTTY) {
    fail('provide --origin when running non-interactively')
  }
  const prompt = createInterface({ input: process.stdin, output: process.stdout })
  const value = await prompt.question('Admin origin [http://localhost:8080]: ')
  prompt.close()
  return normalizedOrigin(value.trim() || 'http://localhost:8080')
}

if (hasFlag('--help')) {
  process.stdout.write(`Chat2API secure environment setup

Usage:
  pnpm setup -- --origin https://gateway.example.com
  pnpm setup -- --origin http://localhost:8080

Options:
  --origin URL         Exact public admin origin
  --force              Back up and replace an existing .env
  --non-interactive    Fail instead of prompting for missing input
  --help               Show this help
`)
  process.exit(0)
}

if (existsSync(environmentPath) && !hasFlag('--force')) {
  fail('.env already exists; use pnpm doctor or pass --force to back it up and replace it')
}

const origin = await resolveOrigin()
const originUrl = new URL(origin)
const isLocal = ['localhost', '127.0.0.1', '::1'].includes(originUrl.hostname)
const content = `# Generated by pnpm setup. Keep this file private.
NODE_ENV=production
CHAT2API_HOST=0.0.0.0
PORT=8080
CHAT2API_DATABASE_PATH=/data/chat2api.sqlite
CHAT2API_LOG_LEVEL=info
CHAT2API_TRUST_PROXY=${isLocal ? 'false' : '1'}
CHAT2API_SECURE_COOKIES=${isLocal ? 'false' : 'true'}

CHAT2API_MASTER_KEY=${randomBytes(32).toString('base64')}
CHAT2API_BOOTSTRAP_API_KEY=${secret()}
CHAT2API_ADMIN_TOKEN=${secret()}
CHAT2API_SESSION_SECRET=${secret(48)}
CHAT2API_ADMIN_ORIGINS=${origin}
CHAT2API_ADMIN_HOSTS=${originUrl.hostname}

CHAT2API_MAX_BODY_BYTES=2097152
CHAT2API_GLOBAL_CONCURRENCY=20
CHAT2API_ACCOUNT_CONCURRENCY=2
CHAT2API_RATE_LIMIT_RPM=60
CHAT2API_DAILY_QUOTA=1000
CHAT2API_REQUEST_TIMEOUT_MS=120000
CHAT2API_FIRST_BYTE_TIMEOUT_MS=30000
CHAT2API_STREAM_IDLE_TIMEOUT_MS=90000
CHAT2API_ACCOUNT_HEALTH_INTERVAL_MS=900000
`

if (existsSync(environmentPath)) {
  const timestamp = new Date().toISOString().replaceAll(/[-:.]/g, '')
  const backupPath = `${environmentPath}.bak.${timestamp}`
  copyFileSync(environmentPath, backupPath)
  chmodSync(backupPath, 0o600)
  process.stdout.write(`Existing .env backed up to ${backupPath}\n`)
}

const descriptor = openSync(environmentPath, 'w', 0o600)
closeSync(descriptor)
writeFileSync(environmentPath, content, { encoding: 'utf8', mode: 0o600 })
chmodSync(environmentPath, 0o600)

const written = readFileSync(environmentPath, 'utf8')
if (!written.includes(`CHAT2API_ADMIN_ORIGINS=${origin}`)) {
  fail('generated environment could not be verified')
}
if (!written.includes(`CHAT2API_ADMIN_HOSTS=${originUrl.hostname}`)) {
  fail('generated admin host could not be verified')
}

process.stdout.write(`Secure environment created at ${environmentPath}

Next:
  pnpm doctor
  docker compose up -d --build

Admin:
  ${origin}/admin/

Retrieve the local admin token only when needed:
  pnpm admin:token
`)
